import { mergeStyleSets } from '@fluentui/react/lib/Styling';
import { IDataGridProps } from './FluentUI-DataGrid';

export const getClassNames = (props: Partial<IDataGridProps>) => {
    return mergeStyleSets({
        container: {
            display: 'flex',
            flexDirection: 'column',
            margin: 'auto',
            padding: '20px',
            height: props?.height ? `${props.height}px` : 'auto',
            width: props?.headerWidth ? `${props.headerWidth}px` : '100%',
        },
        header: {
            backgroundColor: '#638C80',
            color: '#ffffff',
            padding: '10px',
            fontWeight: 'bold',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            borderTopLeftRadius: '9px',
            borderTopRightRadius: '9px',
            marginBottom: '20px',
            width: '100%',
        },
        header2: {
            backgroundColor: '#638C80',
            color: '#ffffff',
            padding: '10px',
            fontWeight: 'bold',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            borderTopLeftRadius: '9px',
            borderTopRightRadius: '9px',
            marginBottom: '20px',
        },
        contentContainer: {
            display: 'flex',
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'flex-start',
            height: props?.contentHeight ? `${props.contentHeight}px` : 'auto',
            width: '100%',
        },
        filterPanel: {
            flex: props?.filterPanelWidth ? `0 0 ${props.filterPanelWidth}px` : '0 0 12%',
            marginRight: '20px',
            backgroundColor: '#ffffff',
            overflowY: 'auto',
            maxHeight: 'auto',
            borderRadius: '10px',
            boxShadow: '0 2px 4px rgba(0,0,0,0.5)',
            border: '1px solid #e0e0e0',
            height: props?.height ? `${props.height}px` : 'auto',
        },
        mainContent: {
            flex: 1,
            display: 'flex',
            flexDirection: 'row',
            overflowY: 'auto',  // Yatay scroll eklemek için
        },
        listContainer: {
            flex: props?.dataListWidth ? `0 0 ${props.dataListWidth}px` : '0 0 65%',
            border: '1px solid #e0e0e0',
            borderRadius: '10px',
            boxShadow: '0 2px 4px rgba(0,0,0,0.5)',
            display: 'flex',
            flexDirection: 'column',
            height: props?.height ? `${props.height}px` : '800px',
            marginRight: '20px',
        },
        listContent: {
            flex: 1,
            overflow: 'auto',
            position: 'relative',
        },
        listScrollContainer: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            overflowX: 'auto',
            overflowY: 'auto',
        },

        detailContainer: {
            flex: props?.detailViewWidth ? `0 0 ${props.detailViewWidth}px` : '0 0 20%',
            border: '1px solid #e0e0e0',
            borderRadius: '10px',
            boxShadow: '0 2px 4px rgba(0,0,0,0.5)',
            display: 'flex',
            flexDirection: 'column',
        },
        searchContainer: {
            padding: '10px',
            borderBottom: '1px solid #e0e0e0',
        },
        content: {
            padding: '10px',
            overflow: 'auto',
            flexGrow: 1,
        },
        table: {
            width: '100%',
            borderCollapse: 'collapse',
            textAlign: 'left',
        },
        tableCell: {
            padding: '10px',
            borderBottom: '1px solid #e0e0e0',
        },
        imageContainer: {
            position: 'relative',
            width: '100%',
            height: '300px',
            marginBottom: '10px',
        },
        detailImage: {
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            cursor: 'pointer',
            border: '1px solid #ccc',
        },
        imageNavigation: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            width: '100%',
            marginBottom: '10px',
        },
        modal: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 0,
            backgroundColor: 'rgba(0,0,0,0.75)',
        },
        modalContent: {
            position: 'relative',
            width: 'auto',
            height: 'auto',
            padding: 0,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'transparent',
        },
        modalImage: {
            maxWidth: '100%',
            maxHeight: '100%',
            objectFit: 'contain',
        },
        modalNavigation: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            position: 'absolute',
            width: '100%',
            top: '50%',
            transform: 'translateY(-50%)',
        },
        filtersContainer: {
            padding: '12px',
            borderBottom: '1px solid #e0e0e0',
            backgroundColor: '#f3f2f1',
        },
        filterItem: {
            marginBottom: '10px',
        },
        filterActions: {
            display: 'flex',
            justifyContent: 'space-between',
            marginTop: '40px',
        },
    });
};
